workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build
jobs:
  build:
    steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command

    deploy-prod:
        steps:
            - checkout
            - run: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"