workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only:
                - master
          requires:
            - build
jobs:
  build:
    machine: true
    steps:
        - checkout # check out the code in the project directory
        # - setup_remote_docker
        - run:
            name: Build image
            command: |
                cd client
                # docker build --no-cache -t seftek/sebastian.party:$CIRCLE_SHA1 .
                docker build -t seftek/sebastian.party:$CIRCLE_SHA1 .
        # - run:
        #     name: Test image
        #     command: |
        #         cd client
        #         docker run -d -p 443:443 --name built-image seftek/sebastian.party:$CIRCLE_SHA1
        #         sleep 20
        #         docker run --network container:built-image appropriate/curl --retry
        #         To fix container testing add certificates
        - run:
            name: Save image to an archive
            command: |
                mkdir docker-image
                docker save -o docker-image/image.tar seftek/sebastian.party

        - persist_to_workspace:
            root: .
            paths:
                - docker-image

  deploy-prod:
        machine: true
        steps:
            - checkout
            - attach_workspace:
                at: workspace
            - run:
                name: Load image
                command: docker load --input workspace/docker-image/image.tar
            - run:
                name: Push image
                command: |
                    docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
                    docker push seftek/sebastian.party:$CIRCLE_SHA1
            - run:
                name: Deploy
                # command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./deploy_project.sh"
                command: |
                    ssh -oStrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "sudo docker stop seb_party0 && sudo docker rm seb_party0"
                    sleep 2
                    ssh -oStrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP "sudo docker run -d -v /var/www/ssl:/etc/ssl/cert:ro --name=seb_party0 -p 443:443 seftek/sebastian.party:"$CIRCLE_SHA1
            - run:
                name: Test image
                command: |
                    sleep 10
                    ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "sudo docker run --network container:seb_party0 appropriate/curl --retry"
